[project]
name = "devops-shield"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[healthcheck]
path = "/"
interval = 30
timeout = 10
retries = 3
