services:
  - type: web
    name: devops-shield
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
