import React, { useState } from 'react';
import './Reports.css';

const MOCK_REPORTS = [
  {
    id: 'rep-001',
    title: 'Weekly SOC2 Compliance Audit',
    date: '2026-02-28',
    status: 'Ready',
    size: '12 KB',
    type: 'JSON'
  },
  {
    id: 'rep-002',
    title: 'Monthly CI/CD Risk Assessment',
    date: '2026-02-01',
    status: 'Ready',
    size: '4 KB',
    type: 'JSON'
  },
  {
    id: 'rep-003',
    title: 'Q1 Vulnerability Scan Results',
    date: '2026-01-15',
    status: 'Archived',
    size: '12.8 MB',
    type: 'CSV'
  },
  {
    id: 'rep-004',
    title: 'Blockchain Audit Trail Export',
    date: '2026-02-27',
    status: 'Ready',
    size: '1.1 MB',
    type: 'JSON'
  }
];

const Reports = ({ addNotification }) => {
  const [downloading, setDownloading] = useState(null);

  const handleDownload = (id) => {
    setDownloading(id);
    addNotification('Preparing report file for download...', 'info');

    // MOCK FILE GENERATION AND TRIGGER DOWNLOAD
    setTimeout(() => {
      const reportMeta = MOCK_REPORTS.find(r => r.id === id) || { type: 'JSON' };
      const extension = reportMeta.type.toLowerCase();

      let fileContent = '';
      let mimeType = 'text/plain;charset=utf-8';

      if (extension === 'json') {
        fileContent = JSON.stringify({ reportId: id, metadata: reportMeta, generatedBy: 'DevOps Shield', status: 'PASS' }, null, 2);
        mimeType = 'application/json';
      } else if (extension === 'csv') {
        fileContent = `Report ID,Title,Date,Status\n${id},"${reportMeta.title}",${reportMeta.date},${reportMeta.status}`;
        mimeType = 'text/csv;charset=utf-8;';
      } else {
        fileContent = `This is a generated ${extension} report for: ${id}\n\nGenerated by DevOps Shield.`;
      }

      const blob = new Blob([fileContent], { type: mimeType });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `report-${id}.${extension}`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setDownloading(null);
      addNotification('Report downloaded successfully.', 'success');
    }, 1500);
  };

  return (
    <div className="page reports-page">
      <header className="page-header">
        <div>
          <h1>Reports & Exports</h1>
          <p className="page-subtitle">Generate, view, and export compliance and security reports.</p>
        </div>
        <button
          className="btn-primary enhance-hover"
          onClick={() => addNotification('Started new report generation task', 'success')}
        >
          <span className="btn-icon">➕</span> Generate New Report
        </button>
      </header>

      <section className="reports-grid">
        <div className="card overview-card reports-stat">
          <div className="stat-icon">📄</div>
          <div>
            <h3>24</h3>
            <p className="muted">Reports Generated (30d)</p>
          </div>
        </div>
        <div className="card overview-card reports-stat">
          <div className="stat-icon">✅</div>
          <div>
            <h3>100%</h3>
            <p className="muted">Compliance Score</p>
          </div>
        </div>
        <div className="card overview-card reports-stat">
          <div className="stat-icon">🕒</div>
          <div>
            <h3>Scheduled</h3>
            <p className="muted">Next auto-run in 2 days</p>
          </div>
        </div>
      </section>

      <section className="card reports-table-card">
        <div className="card-header">
          <h2>Recent Reports</h2>
          <div className="table-actions">
            <button
              className="btn-outline"
              onClick={() => addNotification('Advanced filters opened', 'info')}
            >Filter</button>
          </div>
        </div>
        <div className="table-responsive">
          <table className="devops-table">
            <thead>
              <tr>
                <th>Report Title</th>
                <th>Date Generated</th>
                <th>Status</th>
                <th>Size</th>
                <th>Format</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {MOCK_REPORTS.map(report => (
                <tr key={report.id}>
                  <td>
                    <strong>{report.title}</strong>
                  </td>
                  <td>{report.date}</td>
                  <td>
                    <span className={`badge badge-${report.status === 'Ready' ? 'success' : 'idle'}`}>
                      {report.status}
                    </span>
                  </td>
                  <td className="muted">{report.size}</td>
                  <td>
                    <span className="type-badge">{report.type}</span>
                  </td>
                  <td>
                    <button
                      className={`btn-outline download-btn ${downloading === report.id ? 'downloading' : ''}`}
                      onClick={() => handleDownload(report.id)}
                      disabled={downloading === report.id}
                    >
                      {downloading === report.id ? 'Downloading...' : 'Download'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default Reports;
