name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.114

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Get App URL
        run: |
          flyctl info | grep "App Name\|HOSTNAME"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
